# Generated by Django 3.0.8 on 2020-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.TextField(max_length=3000)),
                ('Disaster_Type', models.CharField(default=' ', max_length=3000)),
            ],
        ),
    ]
