# Generated by Django 3.0.8 on 2020-07-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'get_latest_by': ['Place']},
        ),
    ]
