# Generated by Django 3.0.8 on 2020-07-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earth_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Yes_e', models.TextField(max_length=300)),
                ('No_e', models.TextField(max_length=300)),
            ],
        ),
    ]
