# Generated by Django 3.0.8 on 2020-07-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20200723_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='Country',
            field=models.TextField(default=' ', max_length=3000),
        ),
        migrations.AddField(
            model_name='help',
            name='State',
            field=models.TextField(default=' ', max_length=300),
        ),
    ]
