# Generated by Django 3.0.8 on 2020-07-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_earth_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earth_p',
            name='No_e',
        ),
    ]
