# Generated by Django 3.0.8 on 2020-07-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_earth_p_no_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tsu_p',
            fields=[
                ('earth_p_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.Earth_p')),
            ],
            bases=('chatbot.earth_p',),
        ),
        migrations.CreateModel(
            name='Volc_p',
            fields=[
                ('earth_p_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chatbot.Earth_p')),
            ],
            bases=('chatbot.earth_p',),
        ),
    ]
