# Generated by Django 3.0.8 on 2020-07-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200725_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='help',
            name='State',
        ),
    ]
